// const products = [
//     {
//       id: 0,
//       name: "Apa de toaleta Hugo Boss BOSS Bottled Infinite, 100 ml",
//       price: 393,
//       instock: 10,
//       imgSrc: "../image/Boss-1.jpg",
//       brand: "hugo",
//       gender: "bar",
//       type: "lux",
//       grupType: "acvatice",
//       typeProduct: "apacolonie"
//     },
//     {
//       id: 1,
//       name: "Apa de toaleta Versace Eros, Barbati, 100ml",
//       price: 352,
//       instock: 22,
//       imgSrc: "../image/Versace-2.jpg",
//       brand: "versace",
//       gender: "bar",
//       type: "lux",
//       grupType: "aromatice",
//       typeProduct: "apaparfum"
//     },
//     {
//       id: 2,
//       name: "Apa de toaleta Versace Eros Flame, Barbati, 100ml",
//       price: 420,
//       instock: 10,
//       imgSrc: "../image/Versace-3.jpg",
//       brand: "versace",
//       gender: "bar",
//       type: "cla",
//       grupType: "florale",
//       typeProduct: "apatoaleta"
//     },
//     {
//       id: 3,
//       name: "Apa de toaleta Valentino Born In Roma Uomo, Barbati, 100ml",
//       price: 405,
//       instock: 5,
//       imgSrc: "../image/Valentino-1.jpg",
//       brand: "valentino",
//       gender: "bar",
//       type: "lux",
//       grupType: "acvatice",
//       typeProduct: "apacolonie"
//     },
//     {
//       id: 4,
//       name: "Apa de toaleta Armani Emporio Stronger,Barbati, 100 ml",  
//       price: 399,
//       instock: 4,
//       imgSrc: "../image/Strong-1.jpg",
//       brand: "armani",
//       gender: "bar",
//       type: "cla",
//       grupType: "aromatice",
//       typeProduct: "apaparfum"
//     },
//     {
//       id: 5,
//       name: "Apa de toaleta Versace Eros Pour Femme , Femei, 100ml",
//       price: 350,
//       instock: 40,
//       imgSrc: "../image/Versace-woman.jpg",
//       brand: "versace",
//       gender: "fem",
//       type: "lux",
//       grupType: "florale",
//       typeProduct: "apatoaleta"
//     },
//     {
//       id: 6,
//       name: "Apa de toaleta Paco Rabanne, Lady Million, Femei, 80 ml",
//       price: 420,
//       instock: 8,
//       imgSrc: "../image/paco-woman-2.jpg",
//       brand: "paco",
//       gender: "fem",
//       type: "cla",
//       grupType: "aromatice",
//       typeProduct: "apacolonie"
//     },
//     {
//       id: 7,
//       name: "Apa de toaleta Hugo Boss BOSS Alive Intense, 100 ml",
//       price: 320,
//       instock: 35,
//       imgSrc: "../image/Boss-woman.jpg",
//       brand: "hugo",
//       gender: "fem",
//       type: "lux",
//       grupType: "florale",
//       typeProduct: "apaparfum"
//     },
//     {
//       id: 8,
//       name: "Apa de toaleta Valentino Born In Roma Donna, femei, 100ml",
//       price: 371,
//       instock: 10,
//       imgSrc: "../image/Valentino-woman.jpg",
//       brand: "valentino",
//       gender: "fem",
//       type: "cla",
//       grupType: "lemnoase",
//       typeProduct: "apatoaleta"
//     },
//     {
//       id: 9,
//       name: "Apa de toaleta Paco Rabanne, Invictus Legend, Barbati, 100 ml",
//       price: 290,
//       instock: 3,
//       imgSrc: "../image/invictus-2.jpg",
//       brand: "paco",
//       gender: "bar",
//       type: "lux",
//       grupType: "florale",
//       typeProduct: "apaparfum"
//     },
//     {
//       id: 10,
//       name: "Apa de toaleta Born In Roma Coral Fantasy Donna, femei, 100ml",
//       price: 499,
//       instock: 15,
//       imgSrc: "../image/Valentino-woman-2.jpg",
//       brand: "valentino",
//       gender: "fem",
//       type: "cla",
//       grupType: "acvatice",
//       typeProduct: "apatoaleta"
//     },
//     {
//       id: 11,
//       name: "Apa de colonie Versace Dylan Blue Pour Femme, femei, 100ml",
//       price: 467,
//       instock: 2,
//       imgSrc: "../image/Versace-wom.jpg",
//       brand: "versace",
//       gender: "fem",
//       type: "lux",
//       grupType: "lemnoase",
//       typeProduct: "apacolonie"
//     },
//     {
//       id: 12,
//       name: "Apa de parfum Paco Rabanne Lady Million Empire, femei, 80ml",
//       price: 455,
//       instock: 4,
//       imgSrc: "../image/paco-woman-3.jpg",
//       brand: "paco",
//       gender: "fem",
//       type: "lux",
//       grupType: "aromatice",
//       typeProduct: "apaparfum"
//     },
//   ];
